config/routes.rb
Ukrstyle::Application.routes.draw do
  root :to => 'main#index'
  resources :line_items

  resources :categories
  resources :carts

  resources :general_types

  resources :files
  resources :galleries

  resources :products

  match '/about', :to => 'main#about'
  match '/contact', :to => 'main#contact'

end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :line_items, :dependent => :destroy
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="portfolio_head">
  Корзина
</div>


<div class="dynamic_content">
  <table class="products" width="100%">
    <col width="120">
    <col width="60">
    <col width="60">
    <col width="60">
    <col width="120">
    <col width="20">
    <thead>
    <tr>
      <th></th>
      <th>Товар</th>
      <th>Цена</th>
      <th>Количество</th>
      <th>Итого</th>
      <th></th>
    </tr>
    </thead>
    <tbody>

    <% @cart.line_items.each do |item| %>
        <tr>
          <td>
            <%=image_tag item.product.assets[0].asset.url(:small) if item.product.assets[0] %>
          </td>
          <td valign="top">
            <strong><%= link_to item.product.name, item.product %></strong><br>
          </td>
          <td style="min-width: 100px;">
            <%= item.product.price %> грн.</td>
          <td>
            <%= item.product.minimal_quantity %> шт.
          </td>
          <td>
            <%= item.product.price*item.product.minimal_quantity %> грн.
          </td>
          <td>
            <%= button_to "Удалить", item, method: :delete, data: { confirm: 'Вы уверены?' }%>
          </td>
        </tr>
    <% end %>

    </tbody>
  </table>

</div>

<%= button_to 'Очистить корзину', @cart, :method => :delete, :confirm => 'Вы уверены?' %>